import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpLeft, Check, ChevronDown, Clock3, Hammer, MapPin, Menu, MessageCircle, ShieldCheck, Smartphone, Star, Wrench, X, Zap } from 'lucide-react';

const shots = [`${import.meta.env.BASE_URL}Ammar.jpg`, `${import.meta.env.BASE_URL}Ammar3.jpg`, `${import.meta.env.BASE_URL}Ammar4.jpg`];
const copy = {
  ar: {
    nav: ['المميزات', 'طريقة الاستخدام', 'للفنيين', 'تواصل معنا'],
    kicker: 'خدمات بيتك.. أقرب وأسهل', titleA: 'صنايعي شاطر.', titleB: 'من غير دوشة.',
    intro: 'سباكة، كهرباء، نجارة أو أي شغل في البيت؟ اطلب الخدمة من مكانك، وشوف الصنايعية القريبين منك وتابع طلبك خطوة بخطوة.',
    cta: 'اكتشف التطبيق', second: 'أنا صنايعي', pill: 'كل اللي بيتك محتاجه، في مكان واحد',
    numbers: [['١٢+', 'تخصص منزلي'], ['٢٤/٧', 'اطلب وقت ما تحتاج'], ['خطوة بخطوة', 'تابع حالة طلبك']],
    serviceEyebrow: 'على مقاس بيتك', serviceTitle: 'كل شغل البيت.. له صنايعي', serviceDesc: 'اختار التخصص المناسب، وحدد مكانك، وخلي عمّار يوصّلك بمقدم خدمة قريب منك.',
    services: [['🔧','سباكة'],['💡','كهرباء'],['🪚','نجارة'],['🧱','محارة ومباني'],['❄️','تكييف'],['🎨','نقاشة'],['🪟','زجاج وشبابيك'],['🛋️','أثاث ومفروشات'],['🚪','أبواب'],['🧰','صيانة عامة'],['🏗️','محارة'],['🪨','رخام وسيراميك']],
    howEyebrow: 'طلبك في ٣ خطوات', howTitle: 'ببساطة.. من طلبك لحد ما يخلص',
    steps: [['01','اختار الخدمة','حدد التخصص اللي محتاجه من قائمة خدمات البيت.'],['02','حدد مكانك ووصف المشكلة','ابعت موقعك، اشرح المطلوب، وأرفق صور لو حابب.'],['03','تابع الطلب واستقبل الفني','شوف حالة الطلب وتابع الفني لحد إتمام الشغل.']],
    showcaseTag: 'تجربة واضحة من أول لمسة', showcaseTitle: 'كل التفاصيل.. في إيدك', showcaseDesc: 'واجهة عربية بسيطة، خطوات واضحة، وتفاصيل طلبك قدامك من لحظة ما تختار الخدمة لحد التقييم.',
    benefits: [['⌖','صنايعية قريبين منك','اعرض مقدمي الخدمة حسب التخصص وموقعك الحالي.'],['◷','مواعيد على راحتك','حدد ميعاد يناسبك، وتواصل لمتابعة طلبك.'],['✓','سعر واضح وموافقتك أولًا','راجع السعر المقترح ووافق عليه قبل استكمال الطلب.']],
    proTitle: 'إنت صنايعي؟', proHeadline: 'خلّي شغلك يوصلك لناس أكتر.', proText: 'أنشئ ملفك، اختار التخصصات اللي بتقدمها، وحدد أسعارك وتوفرك. استقبل الطلبات وتابع شغلك من مكان واحد.', proCta:'اسألنا على واتساب عن التسجيل',
    trustTitle:'طلبك تحت عينك.', trustText:'تابع تحديثات الحالة وموقع مقدم الخدمة مباشرة، وقيّم التجربة بعد ما الشغل يخلص.', trustPoints:['إشعارات بتحديثات الطلب','متابعة مباشرة على الخريطة','سجل لطلباتك السابقة'],
    faqTitle:'أسئلة بتتكرر', faqs:[['إزاي أطلب صنايعي؟','اختار التخصص، حدد موقعك، اشرح المشكلة وأرسل الطلب. هتقدر تتابع حالة الطلب من التطبيق.'],['هل أقدر أشتغل كمقدم خدمة؟','أيوه، تقدر تختار وضع الصنايعي، تكمل بياناتك وتضيف التخصصات والأسعار اللي بتقدمها.'],['هل التطبيق متاح بالعربي؟','نعم، التطبيق بيدعم العربي والإنجليزي، وبيبدّل اتجاه الواجهة تلقائيًا.']],
    contactEyebrow:'إحنا هنا للمساعدة', contactTitle:'عندك سؤال؟ كلّمنا.', contactText:'للاستفسارات أو المساعدة، اختار الطريقة اللي تناسبك.', whatsapp:'راسلنا على واتساب', messenger:'راسلنا على ماسنجر', facebook:'تابع صفحتنا على فيسبوك', call:'اتصل بينا', email:'ابعتلنا إيميل',
    footer:'خدمات بيتك بقت أسهل.', made:'تصميم وتطوير الموقع', by:'Muhamad Ammar', rights:'جميع الحقوق محفوظة', top:'فوق', language:'EN'
  },
  en: {
    nav: ['Features', 'How it works', 'For pros', 'Contact'], kicker: 'Home services, closer & simpler', titleA: 'Find your pro.', titleB: 'Skip the hassle.',
    intro: 'Plumbing, electrical, carpentry, or anything around the house? Request a service, find nearby pros, and follow your order from start to finish.', cta:'Explore the app', second:'I’m a pro', pill:'Everything your home needs, in one place',
    numbers: [['12+','home service categories'],['24/7','request when you need'],['Live','follow your order']],
    serviceEyebrow:'Made for your home', serviceTitle:'Every home job has a pro', serviceDesc:'Choose a service, share your location, and Ammar connects you with a nearby provider.',
    services:[['🔧','Plumbing'],['💡','Electrical'],['🪚','Carpentry'],['🧱','Masonry'],['❄️','Air conditioning'],['🎨','Painting'],['🪟','Windows & glass'],['🛋️','Furniture'],['🚪','Doors'],['🧰','General repairs'],['🏗️','Plastering'],['🪨','Tiles & marble']],
    howEyebrow:'Three simple steps', howTitle:'From request to done, made easy', steps:[['01','Choose a service','Pick the home service you need.'],['02','Share the details','Set your location, describe the job, and add photos.'],['03','Follow your order','See order updates and track your provider along the way.']],
    showcaseTag:'A clear experience, from the first tap', showcaseTitle:'Your service, in your hands', showcaseDesc:'An Arabic-first, easy-to-follow experience keeps every order detail close from request to review.', benefits:[['⌖','Nearby providers','Find available pros by service and location.'],['◷','A time that works for you','Choose a suitable time and follow the request.'],['✓','Review the price first','See the proposed price and approve before proceeding.']],
    proTitle:'Are you a service pro?', proHeadline:'Let more customers find your work.', proText:'Create your profile, choose your services, set your rates and availability, then manage incoming requests in one place.', proCta:'Ask us on WhatsApp about joining',
    trustTitle:'Stay in the loop.', trustText:'Follow order updates and provider location, then rate the experience when the work is done.', trustPoints:['Order status notifications','Live map tracking','Your order history'], faqTitle:'Frequently asked questions', faqs:[['How do I request a pro?','Choose a service, share your location, describe the job, and submit. Follow its status in the app.'],['Can I join as a provider?','Yes. Switch to provider mode, complete your profile, then add the services and rates you offer.'],['Is the app available in Arabic?','Yes. The app supports Arabic and English, with the interface direction switching automatically.']],
    contactEyebrow:'We’re here to help', contactTitle:'Have a question? Say hello.', contactText:'For questions or support, reach us in the way that works for you.', whatsapp:'Message on WhatsApp', messenger:'Message us on Messenger', facebook:'Follow us on Facebook', call:'Call us', email:'Send us an email', footer:'Home services, made simpler.', made:'Website designed & built by', by:'Muhamad Ammar', rights:'All rights reserved', top:'Top', language:'عربي'
  }
};

function ButtonLink({ href, children, secondary=false, className='', ...props }) { return <a className={`button ${secondary?'button-quiet':''} ${className}`} href={href} {...props}>{children}</a>; }

export default function App() {
  const [lang,setLang]=useState('ar'), [menu,setMenu]=useState(false), [faq,setFaq]=useState(0);
  const t=copy[lang], ar=lang==='ar';
  const toggle=()=>setLang(ar?'en':'ar');
  return <div className="site" dir={ar?'rtl':'ltr'}>
    <header className="header"><a className="brand" href="#home" aria-label="Ammar home"><span className="brand-mark"><Wrench size={20}/></span><span>عمّار<span className="brand-period">.</span></span></a>
      <nav className={`nav ${menu?'nav-open':''}`}>{t.nav.map((n,i)=><a key={n} href={['#features','#how','#pros','#contact'][i]} onClick={()=>setMenu(false)}>{n}</a>)}</nav>
      <div className="header-actions"><button className="lang-switch" onClick={toggle} aria-label="Switch language">{t.language}</button><ButtonLink href="#contact" secondary className="nav-cta">{ar?'خلّينا نتكلم':'Let’s talk'} <ArrowUpLeft size={15}/></ButtonLink><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div>
    </header>
    <main>
      <section className="hero" id="home"><div className="hero-grid"/><div className="hero-copy"><motion.div className="eyebrow" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><span className="eyebrow-dot"/>{t.kicker}</motion.div><motion.h1 initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.08}}>{t.titleA}<br/><span>{t.titleB}</span></motion.h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><ButtonLink href="#features">{t.cta}<ArrowLeft size={17}/></ButtonLink><a className="text-link" href="#pros">{t.second}<ArrowDown size={15}/></a></div><div className="hero-proof"><div className="avatar-stack"><i>ع</i><i>م</i><i>ا</i><b><Check size={14}/></b></div><span>{t.pill}</span></div></div>
       <motion.div className="hero-visual" initial={{opacity:0,scale:.96,y:20}} animate={{opacity:1,scale:1,y:0}} transition={{duration:.6,delay:.12}}><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-photo-frame"><img src={shots[0]} alt={ar?'واجهة تطبيق عمّار: اختيار التخصصات':'Ammar app service categories screen'}/></div><div className="floating-card location-card"><span className="float-icon"><MapPin size={17}/></span><span><strong>{ar?'فنيين قريبين منك':'Pros near you'}</strong><small>{ar?'حسب موقعك الحالي':'Based on your location'}</small></span><span className="live-dot"/></div><div className="floating-card rating-card"><span className="rating-star"><Star size={17} fill="currentColor"/></span><span><strong>4.9 <small> / 5</small></strong><small>{ar?'تقييمات العملاء':'Customer reviews'}</small></span></div><div className="hero-stamp"><Zap size={17}/><span>{ar?'سهل. سريع. على مزاجك.':'Simple. Fast. On your terms.'}</span></div></motion.div>
       <div className="hero-stats">{t.numbers.map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div>
      </section>

      <section className="services section" id="features"><div className="section-top"><div><div className="eyebrow"><span className="eyebrow-dot"/>{t.serviceEyebrow}</div><h2>{t.serviceTitle}</h2></div><p>{t.serviceDesc}</p></div><div className="service-grid">{t.services.map(([icon,name],i)=><motion.div className="service-tile" key={name} initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.035}}><span>{icon}</span><b>{name}</b><ArrowUpLeft className="tile-arrow" size={16}/></motion.div>)}</div></section>

      <section className="how section" id="how"><div className="how-heading"><div className="eyebrow"><span className="eyebrow-dot"/>{t.howEyebrow}</div><h2>{t.howTitle}</h2></div><div className="steps-grid">{t.steps.map(([number,title,desc],i)=><motion.article className="step-card" key={number} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.12}}><div className="step-top"><span>{number}</span><span className="step-icon">{[<MapPin/>,<Smartphone/>,<Check/>][i]}</span></div><h3>{title}</h3><p>{desc}</p><div className="step-line"><i style={{width:`${(i+1)*33}%`}}/></div></motion.article>)}</div></section>

      <section className="showcase section"><div className="showcase-copy"><div className="eyebrow"><span className="eyebrow-dot"/>{t.showcaseTag}</div><h2>{t.showcaseTitle}</h2><p>{t.showcaseDesc}</p><div className="benefit-list">{t.benefits.map(([icon,title,desc])=><div className="benefit" key={title}><span>{icon}</span><div><b>{title}</b><small>{desc}</small></div></div>)}</div><ButtonLink href="#contact" secondary>{ar?'اسألنا عن التطبيق':'Ask us about the app'}<ArrowLeft size={16}/></ButtonLink></div><div className="screens"><div className="screen screen-back"><img src={shots[1]} alt={ar?'شاشة تحديد الموقع وتفاصيل طلب الخدمة':'Service location and order details screen'}/></div><div className="screen screen-front"><img src={shots[2]} alt={ar?'شاشة متابعة الطلب على الخريطة':'Order tracking map screen'}/></div><div className="screen-note"><MapPin size={16}/>{ar?'موقعك والطلب.. واضحين':'Your location and order, in view'}</div></div></section>

      <section className="pro-section section" id="pros"><div className="pro-copy"><div className="eyebrow eyebrow-light"><span className="eyebrow-dot"/>{t.proTitle}</div><h2>{t.proHeadline}</h2><p>{t.proText}</p><ButtonLink href="https://wa.me/201270527160" target="_blank" rel="noreferrer">{t.proCta}<ArrowLeft size={16}/></ButtonLink></div><div className="pro-graphic"><div className="pro-ring ring-a"/><div className="pro-ring ring-b"/><div className="tool-orb"><Hammer size={48}/></div><div className="pro-chip chip-top"><ShieldCheck size={17}/>{ar?'ملفك المهني':'Your pro profile'}</div><div className="pro-chip chip-bottom"><Clock3 size={17}/>{ar?'حدد مواعيدك':'Set your availability'}</div></div></section>

      <section className="tracking section"><div className="tracking-art"><div className="map-shape"><div className="map-road road-1"/><div className="map-road road-2"/><div className="map-road road-3"/><div className="map-route"/><span className="pin pin-home">⌂</span><span className="pin pin-pro"><Wrench size={17}/></span><span className="map-label">{ar?'فنيك في الطريق':'Your pro is on the way'}</span></div><div className="tracking-caption"><span className="pulse"/>{ar?'تحديث مباشر لمكان الفني':'Live provider location'}</div></div><div className="tracking-copy"><div className="eyebrow"><span className="eyebrow-dot"/>{ar?'متابعة لحظية':'Live updates'}</div><h2>{t.trustTitle}</h2><p>{t.trustText}</p><ul>{t.trustPoints.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></div></section>

      <section className="faq section"><div><div className="eyebrow"><span className="eyebrow-dot"/>{ar?'كل اللي حابب تعرفه':'Good to know'}</div><h2>{t.faqTitle}</h2><p className="faq-sub">{ar?'إجابات سريعة على الأسئلة المهمة.':'Quick answers to common questions.'}</p></div><div className="faq-list">{t.faqs.map(([q,a],i)=><button className={`faq-item ${faq===i?'faq-active':''}`} key={q} onClick={()=>setFaq(faq===i?-1:i)}><span><b>{q}</b>{faq===i&&<small>{a}</small>}</span><ChevronDown size={19}/></button>)}</div></section>

      <section className="contact section" id="contact"><div className="contact-panel"><div className="contact-copy"><div className="eyebrow eyebrow-light"><span className="eyebrow-dot"/>{t.contactEyebrow}</div><h2>{t.contactTitle}</h2><p>{t.contactText}</p></div><div className="contact-actions"><a href="https://wa.me/201270527160" target="_blank" rel="noreferrer"><MessageCircle size={19}/><span>{t.whatsapp}</span><ArrowUpLeft size={16}/></a><a href="https://m.me/61593352823731" target="_blank" rel="noreferrer"><MessageCircle size={19}/><span>{t.messenger}</span><ArrowUpLeft size={16}/></a><a href="https://facebook.com/profile.php?id=61593352823731" target="_blank" rel="noreferrer"><span className="mail-icon">f</span><span>{t.facebook}</span><ArrowUpLeft size={16}/></a><a href="tel:01270527160"><Smartphone size={19}/><span>{t.call}</span><ArrowUpLeft size={16}/></a><a href="mailto:ammarapp.contact@gmail.com"><span className="mail-icon">@</span><span>{t.email}</span><ArrowUpLeft size={16}/></a></div></div></section>
    </main>
    <footer className="footer"><a className="brand" href="#home"><span className="brand-mark"><Wrench size={18}/></span><span>عمّار<span className="brand-period">.</span></span></a><span className="footer-tagline">{t.footer}</span><div className="footer-credit"><span>{t.made}</span><b>{t.by}</b></div><span className="copyright">© {new Date().getFullYear()} {t.rights}</span><a className="to-top" href="#home">{t.top}<ArrowRight size={14}/></a></footer>
  </div>;
}
